// All app copy in EN + FR. Add keys here; use via useCopy() in screens.

export type Locale = "en" | "fr";

const copy = {
  en: {
    // Landing
    landing: {
      eyebrow: "Nuance",
      hero: ["Talk to", "someone ", "real."],
      heroSub: "One stranger. One topic. A few honest minutes. No profiles, no feed, no performance.",
      stats: ["online now", "reach the end", "modes"],
      modesEyebrow: "Four ways to talk",
      ctaPrimary: "Create your account",
      ctaSecondary: "Sign in",
      ctaDemo: "Watch a live demo →",
    },
    // Auth
    auth: {
      signup: { title: "Create your alias.", sub: "An email and password is all we keep. No name, no photo, no profile." },
      signin: { title: "Welcome back.", sub: "Sign in to pick up where the conversation left off." },
      tabSignup: "Create account",
      tabSignin: "Sign in",
      emailLabel: "Email",
      emailPlaceholder: "you@email.com",
      passwordLabel: "Password",
      consent: "By continuing you agree to talk like a person. Moderation and reporting are always on.",
      submitSignup: "Send confirmation email",
      submitSignin: "Sign in",
      trust: "Email · no name · no photo · no credit card",
    },
    // Confirming
    confirming: {
      pending: "Almost there…",
      done: "Check your email.",
      pendingSub: "Setting things up. This takes a moment.",
      doneSub: "We sent a confirmation link. Click it to activate your account and begin onboarding.",
      back: "Back to sign in",
    },
    // Onboarding
    onboarding: {
      steps: ["Step one", "Step two", "Step three", "Step four", "Step five"],
      language: {
        title: "Choose your language.",
        sub: "Everything you read and hear is shown in this language. Talk to anyone in the world — NUANCE auto-translates every message and voice line with AI, so language is never a wall.",
        note: "Pick French and you can still talk to someone in Spanish, Japanese, Arabic — NUANCE handles the rest.",
      },
      intro: {
        title: "How NUANCE works.",
      },
      conduct: {
        title: "The conduct rules.",
        sub: "Scroll to the end to continue.",
        accept: "I'll speak to the person, not the room.",
      },
      alias: {
        title: "Your alias.",
        sub: "NUANCE doesn't need your real name. It gives you a living alias — memorable and still anonymous.",
        identity: "Your identity",
        evolves: "Stage 1 · Family of the night",
        reroll: "Reroll",
        rerollsLeft: (n: number) => `${n} reroll${n !== 1 ? "s" : ""} left`,
      },
      profile: {
        title: "A few details.",
        sub: "Optional — but it helps us match you better. Never public.",
        namePlaceholder: "Or leave blank to use your alias",
        nameLabel: "Display name (optional)",
        ageLabel: "Age range",
        countryLabel: "Country",
        moodLabel: "Mood right now",
        interestsLabel: "Interests (multi-select)",
        voiceLabel: "Voice rooms",
        voiceDesc: "Use push-to-talk for voice alongside text.",
        reconnectsLabel: "Reconnects",
        reconnectsDesc: "Let people request another conversation after a room.",
      },
      continue: "Continue",
      finish: "Enter NUANCE",
      saving: "Just a moment…",
    },
    // Home
    home: {
      greeting: "Good evening",
      title: "Talk to someone real.",
      sub: "A calmer social product: structured rooms, private reconnects, and no performance layer.",
      online: "online now",
      pickAtmosphere: "Pick the atmosphere",
      fourModes: "Four modes",
      openModes: "Open exchange modes",
      quoteEyebrow: "Quote of the day",
      reconnectsEyebrow: "Reconnects",
      reconnectsLink: "See all reconnects →",
      youEnterAs: "You enter as",
    },
    // Start
    start: {
      sub: "Start",
      title: "Choose the exchange.",
      body: "Pick the tone, structure, and duration before you meet the person.",
      findSomeone: (mode: string) => `Find someone for ${mode}`,
      caption: "Any language · auto-translated · trust ≥ 0.45",
      structure: "Structure",
      cadence: "Cadence",
      tone: "Tone",
    },
    // Matchmaking
    matchmaking: {
      searching: "Searching",
      realMatch: "Real match found",
      matchFound: "Match found",
      looking: (mode: string) => `Looking for a ${mode} partner…`,
      found: "Found someone for you.",
      subSearching: "Matching on mode and trust. Language is no barrier — NUANCE translates in real time.",
      subRealFound: "Someone real is ready. Bringing you both to the topic.",
      subAiFound: "Your conversation partner is ready. Bringing you to the topic.",
      cancel: "Cancel search",
    },
    // Topic
    topic: {
      eyebrow: "You both see the same topic",
      accept: "Accept this topic",
      reroll: (n: number) => `Reroll topic · ${n} left`,
      noRerolls: "No rerolls left — rematch",
      bothAccepted: "Both accepted — enter room",
      partnerDeciding: "is deciding…",
      partnerReady: "is ready too",
    },
    // Room
    room: {
      youLabel: "You",
      translated: (lang: string) => `Translated · ${lang}`,
      translatedBanner: (name: string, lang: string) => `Auto-translated · ${name} speaks ${lang}`,
      typingLabel: (lang: string) => `Typing · ${lang}`,
      speakingLabel: (lang: string) => `Speaking · ${lang}`,
      report: "Report this person",
      block: "Block & leave",
      mute: "Mute notifications",
      heldMessage: "Held by moderation — this message wasn't delivered.",
      connectionDrop: "Connection dropped momentarily.",
      placeholder: "Say something honest…",
      voicePlaceholder: "Speaking… press send when done",
      micLive: "Mic is live — your speech appears above",
      caption: "Every message is moderated · report & block always available",
      openingPrompt: (topic: string) => `[Opening] Start the conversation on this topic: "${topic}". Give a brief, genuine opening thought — 1-2 sentences. Don't ask a question yet, just open.`,
    },
    // Summary
    summary: {
      eyebrow: "Summary",
      title: "That's a wrap.",
      with: (alias: string, topic: string) => `with ${alias} on "${topic}"`,
      loading: "Generating your summary…",
      whatHappened: "What happened",
      tone: "Tone",
      whereMet: "Where you met",
      whereDiffered: "Where you differed",
      themes: "Themes",
      questionEyebrow: "A question to sit with",
      recsEyebrow: "Because you talked about this",
      reconnect: "Reconnect?",
      reconnectSub: "If both of you say yes, a private thread opens — no open DMs until then.",
      notNow: "Not this time",
      yesReconnect: "Yes, reconnect",
      reconnectVoted: (alias: string) => `Your vote is in. If ${alias} also votes yes, a thread opens in reconnects.`,
      noReconnect: "No reconnect — that's okay. The conversation still happened.",
      seeReconnects: "See reconnects",
      talkAgain: "Talk to someone new",
      noData: "No conversation data found. Start a room first.",
      tooShort: "The conversation was too short to summarise.",
    },
    // Reconnects
    reconnects: {
      eyebrow: "Reconnects",
      title: "Private and mutual.",
      sub: "No open DMs. If both people say yes, a reconnect thread opens here.",
      note: "Reconnects expire after 30 days of silence. Mutual threads are private — only the two of you can see them.",
    },
    // Account
    account: {
      sub: "Account",
      title: "You, quietly.",
      identityEyebrow: "Your identity",
      trustScore: "Trust score",
      reconnectsCount: "Reconnects",
      reachEnd: "Reach end",
      displaySection: "Display",
      language: "Language",
      theme: "Theme",
      night: "Night",
      day: "Day",
      profileSection: "Profile",
      namePlaceholder: "Display name",
      moodLabel: "Mood",
      interestsLabel: "Interests",
      prefsSection: "Preferences",
      voiceLabel: "Voice rooms",
      voiceDesc: "Use push-to-talk for voice alongside text.",
      reconnectsLabel: "Reconnects",
      reconnectsDesc: "Let people request another conversation after a room.",
      safetySection: "Safety",
      blockedPeople: "Manage blocked people →",
      signOut: "Sign out",
      deleteAccount: "Delete account",
      deleteConfirm: "This is permanent. Your alias, conversations, and reconnects will be gone.",
      keepAccount: "Keep account",
      deleteForever: "Delete forever",
      signingOut: "Signing out…",
    },
    // Demo
    demo: {
      sub: "Live demo · auto-playing",
      topic: "When do you feel most alive?",
      cta: "Try it for real",
    },
    // Nav
    nav: {
      start: "Start",
      home: "Home",
      reconnects: "Reconnects",
      account: "Account",
    },
  },

  fr: {
    landing: {
      eyebrow: "Nuance",
      hero: ["Parler à", "quelqu'un de ", "vrai."],
      heroSub: "Un inconnu. Un sujet. Quelques minutes honnêtes. Pas de profil, pas de fil, pas de performance.",
      stats: ["en ligne", "vont jusqu'au bout", "modes"],
      modesEyebrow: "Quatre façons de parler",
      ctaPrimary: "Créer votre alias",
      ctaSecondary: "Se connecter",
      ctaDemo: "Voir une démo en direct →",
    },
    auth: {
      signup: { title: "Créez votre alias.", sub: "Un email et un mot de passe, c'est tout ce qu'on garde. Pas de nom, pas de photo, pas de profil." },
      signin: { title: "Bon retour.", sub: "Connectez-vous pour reprendre là où la conversation s'est arrêtée." },
      tabSignup: "Créer un compte",
      tabSignin: "Se connecter",
      emailLabel: "Email",
      emailPlaceholder: "vous@email.com",
      passwordLabel: "Mot de passe",
      consent: "En continuant, vous acceptez de parler comme une personne. La modération et le signalement sont toujours actifs.",
      submitSignup: "Envoyer l'email de confirmation",
      submitSignin: "Se connecter",
      trust: "Email · pas de nom · pas de photo · pas de carte bancaire",
    },
    confirming: {
      pending: "Presque là…",
      done: "Vérifiez vos emails.",
      pendingSub: "Mise en place en cours. Un instant.",
      doneSub: "Nous avons envoyé un lien de confirmation. Cliquez dessus pour activer votre compte et commencer l'onboarding.",
      back: "Retour à la connexion",
    },
    onboarding: {
      steps: ["Étape un", "Étape deux", "Étape trois", "Étape quatre", "Étape cinq"],
      language: {
        title: "Choisissez votre langue.",
        sub: "Tout ce que vous lisez et entendez s'affiche dans cette langue. Parlez à n'importe qui dans le monde — NUANCE traduit chaque message et chaque ligne vocale avec l'IA, la langue n'est jamais un obstacle.",
        note: "Choisissez le français et vous pouvez toujours parler à quelqu'un en espagnol, japonais, arabe — NUANCE s'en charge.",
      },
      intro: {
        title: "Comment fonctionne NUANCE.",
      },
      conduct: {
        title: "Les règles de conduite.",
        sub: "Faites défiler jusqu'en bas pour continuer.",
        accept: "Je m'adresse à la personne, pas à la salle.",
      },
      alias: {
        title: "Votre alias.",
        sub: "NUANCE n'a pas besoin de votre vrai nom. Il vous donne un alias vivant — mémorable et toujours anonyme.",
        identity: "Votre identité",
        evolves: "Niveau 1 · Famille de la nuit",
        reroll: "Changer",
        rerollsLeft: (n: number) => `${n} renouvellement${n !== 1 ? "s" : ""} restant${n !== 1 ? "s" : ""}`,
      },
      profile: {
        title: "Quelques détails.",
        sub: "Optionnel — mais cela nous aide à mieux vous matcher. Jamais public.",
        namePlaceholder: "Ou laissez vide pour utiliser votre alias",
        nameLabel: "Nom affiché (optionnel)",
        ageLabel: "Tranche d'âge",
        countryLabel: "Pays",
        moodLabel: "Humeur du moment",
        interestsLabel: "Centres d'intérêt (multi-sélection)",
        voiceLabel: "Salons vocaux",
        voiceDesc: "Utilisez le push-to-talk en plus du texte.",
        reconnectsLabel: "Recontacts",
        reconnectsDesc: "Permettre aux autres de demander une nouvelle conversation après un salon.",
      },
      continue: "Continuer",
      finish: "Entrer dans NUANCE",
      saving: "Un instant…",
    },
    home: {
      greeting: "Bonsoir",
      title: "Parler à quelqu'un de vrai.",
      sub: "Un produit social plus calme : salons structurés, recontacts privés, et aucune couche de performance.",
      online: "en ligne",
      pickAtmosphere: "Choisissez l'ambiance",
      fourModes: "Quatre modes",
      openModes: "Ouvrir les modes d'échange",
      quoteEyebrow: "Citation du jour",
      reconnectsEyebrow: "Recontacts",
      reconnectsLink: "Voir tous les recontacts →",
      youEnterAs: "Vous entrez en tant que",
    },
    start: {
      sub: "Start",
      title: "Choisissez l'échange.",
      body: "Choisissez le ton, la structure et la durée avant de rencontrer la personne.",
      findSomeone: (mode: string) => `Trouver quelqu'un pour ${mode}`,
      caption: "Toute langue · auto-traduit · confiance ≥ 0,45",
      structure: "Structure",
      cadence: "Cadence",
      tone: "Tonalité",
    },
    matchmaking: {
      searching: "Recherche",
      realMatch: "Match réel trouvé",
      matchFound: "Match trouvé",
      looking: (mode: string) => `Recherche d'un partenaire ${mode}…`,
      found: "Quelqu'un a été trouvé pour vous.",
      subSearching: "Matching sur le mode et le score de confiance. La langue n'est pas un obstacle — NUANCE traduit en temps réel.",
      subRealFound: "Quelqu'un est prêt. Vous rejoignez le sujet ensemble.",
      subAiFound: "Votre partenaire de conversation est prêt. Direction le sujet.",
      cancel: "Annuler la recherche",
    },
    topic: {
      eyebrow: "Vous voyez tous les deux le même sujet",
      accept: "Accepter ce sujet",
      reroll: (n: number) => `Nouveau sujet · ${n} restant${n !== 1 ? "s" : ""}`,
      noRerolls: "Plus de renouvellement — nouveau matching",
      bothAccepted: "Les deux ont accepté — entrer dans le salon",
      partnerDeciding: "réfléchit…",
      partnerReady: "est prêt·e aussi",
    },
    room: {
      youLabel: "Vous",
      translated: (lang: string) => `Traduit · ${lang}`,
      translatedBanner: (name: string, lang: string) => `Auto-traduit · ${name} parle ${lang}`,
      typingLabel: (lang: string) => `Écrit · ${lang}`,
      speakingLabel: (lang: string) => `Parle · ${lang}`,
      report: "Signaler cette personne",
      block: "Bloquer et partir",
      mute: "Couper les notifications",
      heldMessage: "Retenu par la modération — ce message n'a pas été envoyé.",
      connectionDrop: "Connexion interrompue un instant.",
      placeholder: "Dites quelque chose d'honnête…",
      voicePlaceholder: "En train de parler… appuyez sur envoyer quand c'est bon",
      micLive: "Le micro est actif — votre voix apparaît ci-dessus",
      caption: "Chaque message est modéré · signalement & blocage toujours disponibles",
      openingPrompt: (topic: string) => `[Ouverture] Commencez la conversation sur ce sujet : "${topic}". Donnez une pensée d'ouverture brève et sincère — 1-2 phrases. Ne posez pas encore de question, ouvrez simplement.`,
    },
    summary: {
      eyebrow: "Résumé",
      title: "C'est terminé.",
      with: (alias: string, topic: string) => `avec ${alias} sur "${topic}"`,
      loading: "Génération du résumé…",
      whatHappened: "Ce qui s'est passé",
      tone: "Tonalité",
      whereMet: "Où vous vous êtes rejoints",
      whereDiffered: "Où vous avez divergé",
      themes: "Thèmes",
      questionEyebrow: "Une question à méditer",
      recsEyebrow: "Parce que vous avez parlé de ça",
      reconnect: "Recontact ?",
      reconnectSub: "Si vous dites tous les deux oui, un fil privé s'ouvre — pas de DM ouvert avant ça.",
      notNow: "Pas cette fois",
      yesReconnect: "Oui, se recontacter",
      reconnectVoted: (alias: string) => `Votre vote est enregistré. Si ${alias} vote aussi oui, un fil s'ouvre dans les recontacts.`,
      noReconnect: "Pas de recontact — c'est bien aussi. La conversation a quand même eu lieu.",
      seeReconnects: "Voir les recontacts",
      talkAgain: "Parler à quelqu'un d'autre",
      noData: "Aucune donnée de conversation trouvée. Commencez un salon d'abord.",
      tooShort: "La conversation était trop courte pour être résumée.",
    },
    reconnects: {
      eyebrow: "Recontacts",
      title: "Privé et mutuel.",
      sub: "Pas de DM ouvert. Si les deux personnes disent oui, un fil de recontact s'ouvre ici.",
      note: "Les recontacts expirent après 30 jours de silence. Les fils mutuels sont privés — seulement vous deux.",
    },
    account: {
      sub: "Compte",
      title: "Vous, discrètement.",
      identityEyebrow: "Votre identité",
      trustScore: "Score de confiance",
      reconnectsCount: "Recontacts",
      reachEnd: "Vont jusqu'au bout",
      displaySection: "Affichage",
      language: "Langue",
      theme: "Apparence",
      night: "Sombre",
      day: "Clair",
      profileSection: "Profil",
      namePlaceholder: "Nom affiché",
      moodLabel: "Humeur",
      interestsLabel: "Centres d'intérêt",
      prefsSection: "Préférences",
      voiceLabel: "Salons vocaux",
      voiceDesc: "Utilisez le push-to-talk en plus du texte.",
      reconnectsLabel: "Recontacts",
      reconnectsDesc: "Permettre aux autres de demander une nouvelle conversation après un salon.",
      safetySection: "Sécurité",
      blockedPeople: "Gérer les personnes bloquées →",
      signOut: "Se déconnecter",
      deleteAccount: "Supprimer le compte",
      deleteConfirm: "C'est permanent. Votre alias, vos conversations et vos recontacts seront supprimés.",
      keepAccount: "Garder le compte",
      deleteForever: "Supprimer définitivement",
      signingOut: "Déconnexion…",
    },
    demo: {
      sub: "Démo en direct · lecture automatique",
      topic: "Quand vous sentez-vous le plus vivant·e ?",
      cta: "L'essayer pour de vrai",
    },
    nav: {
      start: "Start",
      home: "Accueil",
      reconnects: "Recontacts",
      account: "Compte",
    },
  },
} as const;

export type Copy = typeof copy.en;
export function getCopy(locale: Locale): Copy {
  return (copy[locale] ?? copy.en) as Copy;
}
